#!/bin/sh
set -eu

NL='
'

cleanup() {
  err=$?
  if [ $err != 0 ]; then
    printf %s\\n "Terminated on error $err" >&2
  fi
}

trap cleanup 0

#NOTE May get stuck
list=$(runas builder reflector --age 11 --protocol https --fastest 4 --sort score)
test -z "$list" && echo No list >&2 && exit 1

count=0
tosort=
while read -r line; do
  case "$line" in
    "Server = "*)
      tosort=${tosort:+$tosort$NL}$line
      [ $((count += 1)) -eq 3 ] && break
      ;;
    *)
      ;;
  esac
done <<EOF
$list
EOF

buf=$(runas nobody sort -R <<EOF
$tosort
EOF
)

if [ "$count" -ge 3 ]; then
  printf %s\\n "$buf" > /etc/pacman.d/mirrorlist
  #pacman -Syy > /dev/null #might fail if running already
else
  exit 1
fi
